apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  annotations:
  name: my-ec2-upstream
  namespace: gloo-system
spec:
  awsEc2:
    filters:
    - key: gloo-id
    - kvPair:
        key: gloo-tag
        value: group1
    - kvPair:
        key: version
        value: v1.2.3
    region: eu-central-1
    publicIp: true
    port: 81
    secretRef:
      name: gloo-tag-group1
      namespace: default
    roleArn: arn:aws:iam::931713665590:role/GlooGatewayAwsEc2Upstream